added source command
CSSUoB/TeX-Bot-JS pull request #14
Opened 2022-09-05 12:37 UTC by noodleWrecker7

Added simple /source command to close issue #4

2022-09-05 13:56 UTC, LMBishop approved these changes

2022-09-05 21:52 UTC, MattyTheHacker approved these changes

2022-10-08 20:34 UTC, sapphyree requested changes

2022-10-08 20:34 UTC, sapphyree commented on src/commands/source.js
> +    await interaction.reply("TeX bot is an open-source project made specifically for the CSS Discord! You can see and contribute the source code at https://github.com/CSSUoB/TeX-Bot-JS");
`TeX bot` > `TeX`

`...see and contribute the source code` is missing `to` > `contribute to the source code`

2022-10-08 20:37 UTC, noodleWrecker7 commented on src/commands/source.js
> +    await interaction.reply("TeX bot is an open-source project made specifically for the CSS Discord! You can see and contribute the source code at https://github.com/CSSUoB/TeX-Bot-JS");
is fixed in the latest commit

2022-10-08 20:37 UTC, sapphyree approved these changes
LGTM.

2022-10-08 20:37 UTC, merged